import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/course_model.dart';
import '../models/course_statistics_model.dart';

class PdfService {
  PdfService._();

  static Future<void> exportAttendanceReport({
    required CourseModel course,
    required List<CourseStatisticsModel> students,
  }) async {
    final pdf = pw.Document();

    final int totalClasses =
        students.isEmpty ? 0 : students.first.totalClasses;

    final int totalStudents = students.length;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        build: (context) {
          return [
            /// ===============================
            /// Header
            /// ===============================
            pw.Center(
              child: pw.Column(
                children: [
                  pw.Text(
                    "UNIVERSITY ATTENDANCE REPORT",
                    style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 5),
                  pw.Text(
                    "Generated by Attendance Management System",
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ],
              ),
            ),

            pw.Divider(thickness: 2),

            pw.SizedBox(height: 10),

            /// ===============================
            /// Course Information
            /// ===============================
            pw.Text(
              "Course Information",
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 16,
              ),
            ),

            pw.SizedBox(height: 8),

            pw.Text("Course Name : ${course.courseName}"),
            pw.Text("Course Code : ${course.courseCode}"),
            pw.Text("Department  : ${course.department}"),
            pw.Text("Semester    : ${course.semester}"),

            pw.SizedBox(height: 15),

            pw.Text(
              "Total Classes Conducted : $totalClasses",
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),

            pw.Text(
              "Total Students : $totalStudents",
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),

            pw.Text(
              "Generated On : ${DateFormat("dd MMM yyyy  hh:mm a").format(DateTime.now())}",
            ),

            pw.SizedBox(height: 20),

            /// ===============================
            /// Attendance Table
            /// ===============================
            pw.Table.fromTextArray(
              border: pw.TableBorder.all(
                color: PdfColors.grey700,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.grey300,
              ),
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 10,
              ),
              cellStyle: const pw.TextStyle(
                fontSize: 10,
              ),
              headers: const [
                "SL",
                "Student Name",
                "Reg No",
                "Present",
                "Absent",
                "Attendance %",
              ],
              data: List.generate(
                students.length,
                (index) {
                  final s = students[index];

                  final absent =
                      s.totalClasses - s.totalPresent;

                  return [
                    "${index + 1}",
                    s.studentName,
                    s.studentId,
                    "${s.totalPresent}",
                    "$absent",
                    "${s.attendancePercentage.toStringAsFixed(2)}%",
                  ];
                },
              ),
            ),

            pw.SizedBox(height: 40),

            /// ===============================
            /// Signature
            /// ===============================
            pw.Row(
              mainAxisAlignment:
                  pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  children: [
                    pw.Container(
                      width: 180,
                      child: pw.Divider(),
                    ),
                    pw.Text("Teacher Signature"),
                  ],
                ),
                pw.Column(
                  children: [
                    pw.Container(
                      width: 180,
                      child: pw.Divider(),
                    ),
                    pw.Text("Date"),
                  ],
                ),
              ],
            ),

            pw.SizedBox(height: 20),

            pw.Center(
              child: pw.Text(
                "This report was generated automatically by the University Attendance Management System.",
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey700,
                ),
                textAlign: pw.TextAlign.center,
              ),
            ),
          ];
        },
      ),
    );

    final directory =
        await getApplicationDocumentsDirectory();

    final file = File(
      "${directory.path}/${course.courseCode}_Attendance_Report.pdf",
    );

    final bytes = await pdf.save();

    await file.writeAsBytes(bytes);

    await Printing.sharePdf(
      bytes: bytes,
      filename:
          "${course.courseCode}_Attendance_Report.pdf",
    );
  }
}