// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM9wH-ST74dDxqJLzfz8A5vvKeSHTIl9U',
    appId: '1:624964363479:web:580b730ec9031d44373c92',
    messagingSenderId: '624964363479',
    projectId: 'attendance-app-33001',
    authDomain: 'attendance-app-33001.firebaseapp.com',
    storageBucket: 'attendance-app-33001.firebasestorage.app',
    measurementId: 'G-NHWVKYMJW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZqWrMcjzDluwwY0MbE-0zgfRqfOCw1aw',
    appId: '1:624964363479:android:be7e130030065ffc373c92',
    messagingSenderId: '624964363479',
    projectId: 'attendance-app-33001',
    storageBucket: 'attendance-app-33001.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM9wH-ST74dDxqJLzfz8A5vvKeSHTIl9U',
    appId: '1:624964363479:web:d7247b05bb9a2ab5373c92',
    messagingSenderId: '624964363479',
    projectId: 'attendance-app-33001',
    authDomain: 'attendance-app-33001.firebaseapp.com',
    storageBucket: 'attendance-app-33001.firebasestorage.app',
    measurementId: 'G-B99W9JXWVC',
  );
}
